### ISSUE TITLE
Give download modes more self-explanatory names

### ISSUE THREAD

**Issue by planemad** [floscher/josm-mapillary-plugin#4]
This is such an awesome plugin, great job!

The issue I have been having is that the picture layer does not update when the map is panned, and requires removing and readding the layer to refresh the data. Is this a known issue? What would be a good place to file a bug report?

cc @floscher

**Comment by floscher** [comment]
Hi, thank you for the kind words.

Issues can also be filed [in the issue tracker on josm.openstreetmap.org](http://josm.openstreetmap.de/query?status=assigned&status=needinfo&status=new&status=reopened&component=Plugin+mapillary) with the label `Plugin mapillary`. But it's on purpose that this repository has an issues-tab here on GitHub, so you are welcome to open issues here. I'll probably even see them earlier over here than on https://josm.openstreetmap.org.

Regarding your issue, it seems to me, that automatic and semiautomatic mode are currently switched. So currently automatic mode downloads images only for downloaded areas and semiautomatic mode downloads the whole visible area each time you pan. That obviously should be the other way around.

I'll investigate where that comes from and inform you here, when a fix will be released.

For now you should be able to fix this in JOSM by hitting `F12`, click on the Mapillary tab, and switch download mode to semiautomatic.

**Comment by floscher** [comment]
I had a quick look at http://wiki.openstreetmap.org/wiki/JOSM/Plugins/Mapillary#Download_modes and it seems that automatic and semiautomatic download mode were deliberately implemented like that:
* **automatic**: download images only for areas with downloaded OSM-data
* **semiautomatic**: download images for the currently visible viewport on every pan
* **manual**: download only if you select `download mapillary images in current view` from the file menu

I think I'll rename these download modes instead of switching them to make it clearer what these modes do. Maybe to **only areas with OSM-data**, **all visible images** and **no automatic download**.

**Comment by nokutu** [comment]
You are right, those names aren't really self explanatory.

@planemad, you can go to preferences and change the download mode. Looks like you are on manual mode. The mode may change automatically to manual if you pan very far away, because there is a maximum area that can be downloaded.

**Comment by planemad** [comment]
Thanks for the response @floscher @nokutu yup, switching the modes fixes it :+1:

**Comment by floscher** [comment]
Since 710a8f2b91a4510e9d9ea97cd380b1af11853a8a this issue is resolved. The renamed download modes will roll out to all users with the next release.
