### ISSUE TITLE
So, where to submit changes?

### ISSUE THREAD

**Issue by peterneubauer** [floscher/josm-mapillary-plugin#5]
Hi there,
want to get changeset submission in - should I do that here by forking/PR or in SVN?

**Comment by nokutu** [comment]
To edit the svn repo you will need to get credential from the admin, so it should probably be easier just to create a pull request here.

**Comment by PolyglotOpenstreetmap** [comment]
Hi Peter,

So it really depends on whether you are planning to continue working on the plugin code, or if it's a one time contribution. Requesting access to the plugins svn isn't hard ( support@openstreetmap.org) and you usually get access withing a day, depending on TomH's availability.


Jo

**Comment by floscher** [comment]
You are welcome to open pull requests, and if you want I could add you as collaborator to the GitHub-repo.
For PRs the unit tests, test coverage and static code analysis are automatically performed *before* merging into master. Because of that I prefer PRs over directly committing to the SVN-repo, even though I can commit to SVN.

But currently the person merging PRs needs commit-access to the SVN-repo.

I'd also be open to making this project GitHub-only. Using git-svn adds an extra amount of work to each commit, which is rather unnecessary, because all committers are familiar with git. There were some problems in the past that Github-only plugins were marked as "untrusted" and not automatically translated via Launchpad, but that might have changed in the meantime.

**Comment by peterneubauer** [comment]
HI there, I have started to make changesets work, see https://github.com/mapillary/josm-mapillary-plugin but it's a few days until we have the Mapillary API in place so I can make the URLs final. Will wait with a PR until then. Thanks guys!

**Comment by floscher** [comment]
@peterneubauer Now there is one: [`731792e`/.idea/codeStyleSettings.xml](https://github.com/floscher/josm-mapillary-plugin/blob/731792ee4cead8713a3d82a4fe29c66d3b2c8871/.idea/codeStyleSettings.xml)
If you are using the directory-based settings in IntelliJ, it should automatically pick up that file.

I'll close this issue for now. When your changes are ready to submit, just [open a new PR](https://github.com/floscher/josm-mapillary-plugin/compare/master...mapillary:master?expand=1) . Would you mind if I'd already go ahead and cherry-pick some of [the changes you made](https://github.com/mapillary/josm-mapillary-plugin/compare/d7bd3b76f070a1ad28039ef0c82d67717438f00e...d4a2799c614aae7c795534705c3efb439fbb4de4) that are rather unrelated to changesets (the debugJosm-task, renaming of methods, …) and put them into our master-branch before the changeset-feature is ready to merge?
